kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: nfs
  resources:
    requests:
      storage: {{ .Values.resources.requests.storage }}
