filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
    - versionStream/src/fake-secrets.yaml.gotmpl
repositories:
- name: cdf
  url: https://cdfoundation.github.io/tekton-helm-chart
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: external-secrets
  url: https://external-secrets.github.io/kubernetes-external-secrets
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
- name: codecentric
  url: https://codecentric.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: vitech-sdlc
  url: https://vitech-team.github.io/sdlc-charts
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  version: 1.0.17
  name: jxboot-helmfile-resources
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: external-secrets/kubernetes-external-secrets
  version: 5.2.0
  name: kubernetes-external-secrets
  namespace: secret-infra
  values:
  - versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: jx3/jenkins-x-crds
  version: 3.0.5
  name: jenkins-x-crds
  namespace: jx
  values:
  - versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: jx3/jx-pipelines-visualizer
  version: 0.0.53
  name: jx-pipelines-visualizer
  namespace: jx
  values:
  - versionStream/charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: jx3/jx-preview
  version: 0.0.116
  name: jx-preview
  namespace: jx
  forceNamespace: ""
  skipDeps: null
- chart: stable/nginx-ingress
  version: 1.39.1
  name: nginx-ingress
  namespace: nginx
  values:
  - versionStream/charts/stable/nginx-ingress/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: cdf/tekton-pipeline
  version: 0.18.0-1
  name: tekton-pipeline
  namespace: tekton-pipelines
  values:
  - versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: jenkins-x/lighthouse
  version: 0.0.879
  name: lighthouse
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: jenkins-x/nexus
  version: 0.1.35
  name: nexus
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/nexus/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: stable/chartmuseum
  version: 2.4.1
  name: chartmuseum
  namespace: jx
  values:
  - versionStream/charts/stable/chartmuseum/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: banzaicloud-stable/vault-operator
  version: 1.3.0
  name: vault-operator
  namespace: secret-infra
  forceNamespace: ""
  skipDeps: null
- chart: jx3/vault-instance
  version: 1.0.1
  name: vault-instance
  namespace: secret-infra
  forceNamespace: ""
  skipDeps: null
- chart: jx3/pusher-wave
  version: 0.4.12
  name: pusher-wave
  namespace: secret-infra
  forceNamespace: ""
  skipDeps: null
- chart: jx3/jx-build-controller
  version: 0.0.14
  name: jx-build-controller
  namespace: jx
  values:
  - versionStream/charts/jx3/jx-build-controller/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: ./charts/dev/tektonpipelines
  version: 0.1.0
  name: tektonpipelines
  namespace: jx
  forceNamespace: ""
  skipDeps: null
- chart: vitech-sdlc/keycloak
  name: keycloak
  namespace: keycloak
  values:
  - charts/vitech-sdlc/keycloak/values.yaml
  - charts/vitech-sdlc/keycloak/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: prometheus-community/kube-prometheus-stack
  version: 10.3.3
  name: monitoring
  namespace: monitoring
  values:
  - charts/prometheus-community/kube-prometheus-stack/values.yaml
  - charts/prometheus-community/kube-prometheus-stack/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: vitech-sdlc/monitoring
  version: 0.1.0
  name: prometheus-monitors
  namespace: monitoring
  forceNamespace: ""
  skipDeps: null
  values:
    - charts/vitech-sdlc/monitoring/values.yaml
- chart: vitech-sdlc/secret
  version: 0.1.0
  name: secret
  namespace: jx
  forceNamespace: ""
  skipDeps: null
  values:
    - charts/vitech-sdlc/secret/values.yaml
templates: {}
missingFileHandler: ""
renderedvalues: {}
