filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: monitoring
repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: vitech-sdlc
  url: https://vitech-team.github.io/sdlc-charts
releases:
- chart: prometheus-community/kube-prometheus-stack
  version: 10.3.3
  name: monitoring
  values:
  - ../../charts/prometheus-community/kube-prometheus-stack/values.yaml
  - ../../charts/prometheus-community/kube-prometheus-stack/values.yaml.gotmpl
  - jx-values.yaml
- chart: vitech-sdlc/monitoring
  version: 0.1.0
  name: prometheus-monitors
  values:
  - ../../charts/vitech-sdlc/monitoring/values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
