apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: large-tests
    context: "large-tests"
    always_run: false
    optional: true
    source: "large-tests-check-pipeline.yaml"
  postsubmits:
