apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-actuator
  namespace: monitoring
  labels:
    release: "monitoring"
spec:
  podMetricsEndpoints:
    - path: /prometheus
      port: metrics
      scheme: http
  jobLabel: spring-actuator
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      spring-actuator: "true"
